// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
)

type Instrument struct {
	ID             int32
	UserID         int32
	IsActive       sql.NullBool
	InstrumentName sql.NullString
}

type Invite struct {
	ID         int32
	UserID     int32
	Remittee   sql.NullString
	Status     sql.NullString
	InviteType sql.NullString
}

type Metadatum struct {
	ID          int32
	UserID      int32
	UserType    sql.NullString
	Photo       sql.NullString
	Description sql.NullString
	Status      sql.NullString
	Address     sql.NullString
}

type Repertoire struct {
	ID          int32
	UserID      int32
	Name        sql.NullString
	IsActive    sql.NullBool
	MusicListID sql.NullInt32
}

type Solicitation struct {
	ID         int32
	UserID     int32
	Remittee   sql.NullString
	Status     sql.NullString
	InviteType sql.NullString
}

type User struct {
	ID       int32
	Name     string
	Email    string
	Password string
}
